[![Open in Visual Studio Code](https://classroom.github.com/assets/open-in-vscode-718a45dd9cf7e7f842a935f5ebbe5719a5e09af4491e668f4dbf3b35d5cca122.svg)](https://classroom.github.com/online_ide?assignment_repo_id=10249350&assignment_repo_type=AssignmentRepo)
= TP4 R2.03 Qualité - Projet Maven
Dylan Latapie <dylan.ltp@gmail.com>
v1, 2023-02-23 : Initial draft
//---------------------------------------------------------------
=== Documentation du projet

Pour utiliser le projet vous devez suivre les instructions suivantes :

. Tout d'abord, nettoyez le projet Maven avec la commande :
+
....
mvn clean
....

. Ensuite, pour compiler l'application utilisez la commande :
+
....
mvn compile
....

. Lancez la fabrication d'une version exécutable avec la commande :
+
....
mvn package
....
+
NOTE: Lorsque vous exécutez `mvn package`, la javadoc se génère automatiquement. Vous la trouverez sous forme de site dans le dossier target/apidocs ET sous forme de jar dans le dossier target (tp_qualite-1.0-javadoc.jar).

. Pour générer la Javadoc du projet manuellement, vous pouvez exécuter la commande :
+
....
mvn javadoc:javadoc
....
+
NOTE: Lors de l'exécution de `mvn javadoc:javadoc`, la javadoc se générera dans le dossier target/site/apidocs.

. Pour tester la version exécutable, exécutez la commande :
+
....
java -jar target/tp_qualite-1.0.jar
....