= TP4 R2.03 Qualité - Projet Maven
Dylan Latapie <dylan.ltp@gmail.com>
v1, 2023-02-23 : Initial draft
//---------------------------------------------------------------
=== Documentation du projet

Pour utiliser le projet vous devez suivre les instructions suivantes :

. Tout d'abord, nettoyez le projet Maven avec la commande :
+
....
mvn clean
....

. Ensuite, pour compiler l'application utilisez la commande :
+
....
mvn compile
....

. Lancez la fabrication d'une version exécutable avec la commande :
+
....
mvn package
....
+
NOTE: Lorsque vous exécutez `mvn package`, la javadoc se génère automatiquement. Vous la trouverez sous forme de site dans le dossier target/apidocs ET sous forme de jar dans le dossier target (tp_qualite-1.0-javadoc.jar).

. Pour générer la Javadoc du projet manuellement, vous pouvez exécuter la commande :
+
....
mvn javadoc:javadoc
....
+
NOTE: Lors de l'exécution de `mvn javadoc:javadoc`, la javadoc se générera dans le dossier target/site/apidocs.

. Pour tester la version exécutable, exécutez la commande :
+
....
java -jar target/tp_qualite-1.0.jar
....